# Generated by Django 6.1.1 on 2026-09-18 13:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_bp', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)], verbose_name='Systolic BP (mmHg)')),
                ('diastolic_bp', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)], verbose_name='Diastolic BP (mmHg)')),
                ('pulse_rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(250)], verbose_name='Pulse rate (bpm)')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('25.0')), django.core.validators.MaxValueValidator(Decimal('45.0'))], verbose_name='Temperature (°C)')),
                ('spo2', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='SpO₂ (%)')),
                ('respiratory_rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(80)], verbose_name='Respiratory rate (breaths/min)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('400'))], verbose_name='Weight (kg)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.30')), django.core.validators.MaxValueValidator(Decimal('2.50'))], verbose_name='Height (m)')),
                ('presenting_complaint', models.TextField(blank=True, help_text='What the patient says is wrong, so the doctor has context before calling them in.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vitals_recorded', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.visit')),
            ],
            options={
                'verbose_name': 'vitals',
                'verbose_name_plural': 'vitals',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
