# Generated by Django 6.1.1 on 2026-09-22 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_visit_one_open_visit_per_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('department', models.CharField(help_text='Which part of the clinic the patient is coming to.', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], default='booked', max_length=20)),
                ('outcome_note', models.CharField(blank=True, help_text='Why it was cancelled, or anything said when it was missed.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.ForeignKey(blank=True, help_text='The named member of staff, where the clinic books by person.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_booked', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='patients.visit')),
            ],
            options={
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['scheduled_for', 'status'], name='appointment_schedul_ee1bbd_idx'), models.Index(fields=['patient', 'scheduled_for'], name='appointment_patient_ce499b_idx')],
            },
        ),
    ]
