# Generated by Django 6.1.1 on 2026-09-22 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_invoice_payment_invoiceline_and_more'),
        ('patients', '0002_visit_one_open_visit_per_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('clinical_details', models.TextField(blank=True, help_text='Why it was ordered — what the department needs to know before acting.')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='billing.invoiceline')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_placed', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='billing.service')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='patients.visit')),
            ],
            options={
                'ordering': ['ordered_at'],
                'indexes': [models.Index(fields=['status', 'ordered_at'], name='orders_orde_status_9cd221_idx')],
            },
        ),
    ]
