# Generated by Django 6.1.1 on 2026-09-19 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short stable code used on bills and reports, e.g. LAB-MPS.', max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(choices=[('consultation', 'Consultation'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('procedure', 'Procedure / Injection room'), ('other', 'Other')], help_text='Which department performs it — this is what gates the queues.', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit price (KES)')),
                ('is_active', models.BooleanField(default=True, help_text='Retired services stay here so old bills still read correctly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['department', 'name'],
                'indexes': [models.Index(fields=['department', 'is_active'], name='billing_ser_departm_1522ef_idx')],
            },
        ),
    ]
