# Generated by Django 6.1.1 on 2026-09-18 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='MRN')),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('residence', models.CharField(blank=True, help_text='Area or address', max_length=120)),
                ('national_id', models.CharField(blank=True, help_text='Adults only; left blank for minors.', max_length=20)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=120)),
                ('next_of_kin_relationship', models.CharField(blank=True, help_text='e.g. spouse, parent, sibling', max_length=40)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_triage', 'Awaiting triage'), ('awaiting_consultation', 'Awaiting consultation'), ('in_consultation', 'In consultation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='awaiting_triage', max_length=30)),
                ('billing_mode', models.CharField(choices=[('pay_per_service', 'Pay per service'), ('consolidated', 'Consolidated')], default='pay_per_service', max_length=20)),
                ('is_urgent', models.BooleanField(default=False, help_text="Set at triage when vitals are out of range; prioritises the doctor's queue.")),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits_started', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_number'], name='patients_pa_phone_n_933975_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status', '-started_at'], name='patients_vi_status_a0cce1_idx'),
        ),
    ]
