# Generated by Django 6.1.1 on 2026-09-19 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['awaiting_triage', 'awaiting_consultation', 'in_consultation'])), fields=('patient',), name='one_open_visit_per_patient'),
        ),
    ]
