# Generated by Django 6.1.1 on 2026-09-22 12:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_invoice_payment_invoiceline_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, help_text='e.g. 1 tablet', max_length=60)),
                ('frequency', models.CharField(blank=True, help_text='e.g. three times a day', max_length=60)),
                ('duration', models.CharField(blank=True, help_text='e.g. 5 days', max_length=60)),
                ('instructions', models.CharField(blank=True, help_text='e.g. after food', max_length=200)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_dispensed', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prescription', to='orders.order')),
            ],
            options={
                'ordering': ['-order__ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('generic_name', models.CharField(blank=True, max_length=120)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream or ointment'), ('drops', 'Drops'), ('sachet', 'Sachet'), ('consumable', 'Consumable')], max_length=20)),
                ('strength', models.CharField(blank=True, help_text='e.g. 500 mg', max_length=40)),
                ('unit', models.CharField(default='unit', help_text='What one counted unit is — tablet, ml, sachet, piece.', max_length=20)),
                ('reorder_level', models.PositiveIntegerField(default=0, help_text='Falls to this or below and it shows as low stock.')),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.OneToOneField(blank=True, help_text='The priced service this is dispensed as. Blank for consumables.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_item', to='billing.service')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=40)),
                ('quantity_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='What the clinic paid per unit — this is what makes profit reportable.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Unit cost (KES)')),
                ('expires_on', models.DateField()),
                ('supplier', models.CharField(blank=True, max_length=120)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_received', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='pharmacy.stockitem')),
            ],
            options={
                'ordering': ['expires_on', 'received_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Positive in, negative out.')),
                ('reason', models.CharField(choices=[('received', 'Received'), ('dispensed', 'Dispensed'), ('consumed', 'Used in a procedure'), ('wastage', 'Wastage or breakage'), ('expired', 'Written off, expired'), ('correction', 'Stock count correction')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pharmacy.stockbatch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pharmacy.stockitem')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pharmacy.prescription')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['item', 'expires_on'], name='pharmacy_st_item_id_09dc49_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', '-recorded_at'], name='pharmacy_st_item_id_4781f4_idx'),
        ),
    ]
