# Generated by Django 6.1.1 on 2026-09-22 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_visit_one_open_visit_per_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(help_text='What the patient came in for.', verbose_name='C/C')),
                ('history_of_presenting_illness', models.TextField(blank=True, verbose_name='HPI')),
                ('past_medical_history', models.TextField(blank=True, verbose_name='Past medical and surgical history')),
                ('drug_reactions', models.TextField(blank=True, help_text='Known allergies and adverse reactions.', verbose_name='Drug reactions')),
                ('gynaecological_history', models.TextField(blank=True, verbose_name='Gynaecological history')),
                ('obstetric_history', models.TextField(blank=True, verbose_name='Obstetric history')),
                ('family_history', models.TextField(blank=True, verbose_name='Family history')),
                ('examination_findings', models.TextField(blank=True)),
                ('diagnosis', models.CharField(blank=True, max_length=200)),
                ('icd10_code', models.CharField(blank=True, help_text='Optional; carried for reporting rather than required at the bedside.', max_length=10, verbose_name='ICD-10 code')),
                ('treatment_plan', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='patients.visit')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
