# Generated by Django 6.1.1 on 2026-09-22 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_invoice_payment_invoiceline_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('stool', 'Stool'), ('swab', 'Swab'), ('sputum', 'Sputum'), ('other', 'Other')], max_length=20)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('findings', models.TextField(blank=True, help_text='The result, as it is reported.')),
                ('is_abnormal', models.BooleanField(default=False, help_text="Flagged by the technician; shows against the result in the doctor's queue.")),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specimens_collected', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lab_result', to='orders.order')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_results_recorded', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_results_released', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order__ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('stool', 'Stool'), ('swab', 'Swab'), ('sputum', 'Sputum'), ('other', 'Other')], max_length=20)),
                ('reference_range', models.CharField(blank=True, help_text='What normal looks like, shown beside the result as it is typed.', max_length=120)),
                ('preparation', models.CharField(blank=True, help_text='What the patient must do first, e.g. fast for 8 hours.', max_length=200)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test', to='billing.service')),
            ],
            options={
                'ordering': ['service__name'],
            },
        ),
    ]
